server.port=8092

aes.secret.key=MAx6fbSxguOl/UpFpIyXLA==

logging.level.com.raissa.extranet=DEBUG

payments.api.url=http://localhost:8082
connect.api.server=3.136.16.248:5432
connect.api.username=postgres
connect.api.password=postgres13
connect.api.driver-class-name=org.postgresql.Driver
raissa.seguridad.dias.expiracion.clave=90

server.forward-headers-strategy=framework

apisraissa.api.url=https://raissaob.com/api/bffapis
raissa.bff.apikey=hN7GRzbe6G2yIpzuMaRCE3BVaAiaRi6nvSCQ+80Zkrhhwu1PduX0+9Q5vNd8V6gH