server.port=8092

aes.secret.key=MAx6fbSxguOl/UpFpIyXLA==

logging.level.com.raissa.extranet=DEBUG

payments.api.url=http://localhost:8091
connect.api.server=localhost:3308
connect.api.username=postgres
connect.api.password=123
connect.api.driver-class-name=org.postgresql.Driver
raissa.seguridad.dias.expiracion.clave=90

apisraissa.api.url=http://100.122.165.121:8089
#apisraissa.api.url=https://raissaob.com/api/bffapis
raissa.bff.apikey=hN7GRzbe6G2yIpzuMaRCE3BVaAiaRi6nvSCQ+80Zkrhhwu1PduX0+9Q5vNd8V6gH