aes.secret.key=MAx6fbSxguOl/UpFpIyXLA==

payments.api.url=http://localhost:8091
connect.api.server=3.136.16.248:5432
connect.api.username=postgres
connect.api.password=postgres13
connect.api.driver-class-name=org.postgresql.Driver
raissa.seguridad.dias.expiracion.clave=90

server.forward-headers-strategy=framework

apisraissa.api.url=https://raissaob.com/api/bffapis
raissa.bff.apikey=hN7GRzbe6G2yIpzuMaRCE3BVaAiaRi6nvSCQ+80Zkrhhwu1PduX0+9Q5vNd8V6gH

# ============================================
# RABBITMQ - CONSUMIDOR (DEV)
# ============================================
spring.rabbitmq.host=3.136.16.248
spring.rabbitmq.port=5672
spring.rabbitmq.username=raissa
spring.rabbitmq.password=S3cr3t0
spring.rabbitmq.virtual-host=dev

# Colas a consumir
rabbitmq.queues.payments.consulta=payments.consulta.transferencia
rabbitmq.queues.payments.aplicacion=payments.aplicacion.transferencia

# Configuración de consumidores
rabbitmq.listener.validacion.concurrent-consumers=10
rabbitmq.listener.validacion.max-concurrent-consumers=20
rabbitmq.listener.validacion.prefetch=5
rabbitmq.listener.validacion.timeout=240000

# Para EJECUCIÓN (larga - 1.5 a 3 min)
rabbitmq.listener.ejecucion.concurrent-consumers=10
rabbitmq.listener.ejecucion.max-concurrent-consumers=20
rabbitmq.listener.ejecucion.prefetch=5
rabbitmq.listener.ejecucion.timeout=240000

# ============================================
# LOGGING
# ============================================
logging.level.com.raissapayments.conector=DEBUG
logging.level.org.springframework.amqp=DEBUG